import { test, expect } from '@playwright/test';
import { login } from '../fixtures/auth';
import { LOCATIONS, PRODUCTS, runId, url } from '../fixtures/constants';
import { createOutboundWithLineItem, expectActiveStep, fetchStockMovement } from '../fixtures/outbound';
import { captureStep, resetStepCounter } from '../fixtures/screenshots';

/**
 * Flow 4: Create and process an outbound stock movement.
 *
 * Golden path: create an outbound stock movement from Main Warehouse to the
 * demo Boston Warehouse, add a line item, then process it through the Edit
 * and Pick wizard steps. Asserts on the requisition status transitions and
 * on the autogenerated picklist (a real PicklistItem allocating stock from a
 * bin, with the full requested quantity picked).
 */
test('creates and processes an outbound stock movement through picking', async ({ page }) => {
  resetStepCounter();
  const FLOW = 'outbound-stock-movement';
  const QTY = 4;
  const description = `Characterization outbound ${runId()}`;

  await login(page);

  const stockMovementId = await createOutboundWithLineItem(page, {
    productName: PRODUCTS.lamivudine.name,
    qty: QTY,
    description,
  });
  await captureStep(page, FLOW, 'edit-step');

  // After Add items -> Next the requisition has left CREATED.
  const afterAddItems = await fetchStockMovement(page, stockMovementId);
  expect(afterAddItems.identifier).toMatch(/^[0-9A-Z]{6}$/);
  expect(afterAddItems.origin.name).toBe(LOCATIONS.mainWarehouse.name);
  expect(afterAddItems.destination.name).toBe(LOCATIONS.bostonWarehouse.name);
  expect(afterAddItems.statusCode).not.toBe('CREATED');

  // --- Edit -> Pick: entering the pick step autogenerates the picklist ---
  await page.click('button:has-text("Next")');
  await expectActiveStep(page, 'Pick');
  // Wait for the autogenerated picklist rows to render before touching the
  // API (entering the step kicks off picklist generation server-side).
  await page.locator('.rt-tr, [role="row"]').filter({ hasText: PRODUCTS.lamivudine.name }).first().waitFor();
  await page.waitForLoadState('networkidle');
  await captureStep(page, FLOW, 'pick-step');

  // --- Outcome assertions on real data ---
  const picked = await fetchStockMovement(page, stockMovementId);
  expect(['PICKING', 'PICKED']).toContain(picked.statusCode);

  const itemsRes = await page.request.get(
    url(`/api/stockMovements/${stockMovementId}/stockMovementItems?stepNumber=4&refreshPicklistItems=false`),
  );
  expect(itemsRes.status()).toBe(200);
  const pickPageItems = (await itemsRes.json()).data;
  expect(pickPageItems).toHaveLength(1);
  expect(pickPageItems[0].productName ?? pickPageItems[0].product?.name).toContain(
    PRODUCTS.lamivudine.name,
  );
  const picklistItems = pickPageItems[0].picklistItems;
  expect(picklistItems.length).toBeGreaterThan(0);
  const totalPicked = picklistItems.reduce(
    (sum: number, i: { quantityPicked: number }) => sum + i.quantityPicked,
    0,
  );
  expect(totalPicked).toBe(QTY);
});
