import {
  BUDGET_CODE_OPTIONS,
  ORDER_ADJUSTMENT_BY_ID,
  ORDER_ADJUSTMENT_TYPE_OPTIONS,
  ORDER_ADJUSTMENTS,
  ORDER_API,
  ORDER_BY_ID,
  ORDER_COMMENTS,
  ORDER_DETAILS,
  ORDER_DOCUMENT_TYPES,
  ORDER_DOCUMENTS,
  ORDER_INVOICES,
  ORDER_ITEM_OPTIONS,
  ORDER_ITEM_SUMMARIES,
  ORDER_ITEMS,
  ORDER_PENDING_ITEMS,
  ORDER_PRINT,
  ORDER_SHIPMENTS,
  ORDER_SUMMARIES,
} from 'api/urls';
import apiClient from 'utils/apiClient';

export default {
  getOrders: (config) => apiClient.get(ORDER_API, config),
  getOrder: (id, config) => apiClient.get(ORDER_BY_ID(id), config),
  getOrderDetails: (id, config) => apiClient.get(ORDER_DETAILS(id), config),
  getOrderItems: (id, config) => apiClient.get(ORDER_ITEMS(id), config),
  getOrderShipments: (id, config) => apiClient.get(ORDER_SHIPMENTS(id), config),
  getOrderInvoices: (id, config) => apiClient.get(ORDER_INVOICES(id), config),
  getOrderDocuments: (id, config) => apiClient.get(ORDER_DOCUMENTS(id), config),
  getOrderComments: (id, config) => apiClient.get(ORDER_COMMENTS(id), config),
  getOrderAdjustments: (id, config) => apiClient.get(ORDER_ADJUSTMENTS(id), config),
  getOrderPrintData: (id, config) => apiClient.get(ORDER_PRINT(id), config),
  createComment: (id, payload) => apiClient.post(ORDER_COMMENTS(id), payload),
  getPendingItems: (config) => apiClient.get(ORDER_PENDING_ITEMS, config),
  getDocumentTypeOptions: (config) => apiClient.get(ORDER_DOCUMENT_TYPES, config),
  uploadDocument: (id, formData) => apiClient.post(ORDER_DOCUMENTS(id), formData),
  getOrderItemOptions: (id, config) => apiClient.get(ORDER_ITEM_OPTIONS(id), config),
  getAdjustment: (id, adjustmentId, config) =>
    apiClient.get(ORDER_ADJUSTMENT_BY_ID(id, adjustmentId), config),
  createAdjustment: (id, payload) => apiClient.post(ORDER_ADJUSTMENTS(id), payload),
  updateAdjustment: (id, adjustmentId, payload) =>
    apiClient.put(ORDER_ADJUSTMENT_BY_ID(id, adjustmentId), payload),
  getOrderAdjustmentTypeOptions: (config) => apiClient.get(ORDER_ADJUSTMENT_TYPE_OPTIONS, config),
  getBudgetCodeOptions: (config) => apiClient.get(BUDGET_CODE_OPTIONS, config),
  getOrderSummaries: (config) => apiClient.get(ORDER_SUMMARIES, config),
  getOrderItemSummaries: (config) => apiClient.get(ORDER_ITEM_SUMMARIES, config),
};
