import { Page, expect } from '@playwright/test';
import { LOCATIONS, today, url } from './constants';
import { selectByFormField, selectInside } from './react-select';

/**
 * Creates an outbound stock movement from Main Warehouse to the demo Boston
 * Warehouse depot with a single line item, and advances the wizard from
 * "Add items" onto the "Edit" step. Returns the stock movement id.
 */
export async function createOutboundWithLineItem(
  page: Page,
  { productName, qty, description }: { productName: string; qty: number; description: string },
): Promise<string> {
  // Create
  await page.goto(url('/stockMovement/createOutbound?direction=OUTBOUND'));
  await page.waitForSelector('#description');
  await page.fill('#description', description);
  await selectByFormField(page, 'Destination', LOCATIONS.bostonWarehouse.name);
  await selectByFormField(page, 'Requested By', 'admin', 'admin');
  await page.locator('#dateRequested, input[name="dateRequested"]').first().fill(today());
  await page.keyboard.press('Escape');
  await selectByFormField(page, 'Request type', 'Stock', 'Stock');
  await page.click('button:has-text("Next")');
  await page.waitForURL(/createOutbound\/[a-zA-Z0-9]+/);
  const stockMovementId = page.url().match(/createOutbound\/([a-zA-Z0-9]+)/)![1];

  // Add items, then Next onto the Edit step
  await page.locator('input[id^="lineItems"][id$="quantityRequested"]').first().waitFor();
  const row = page
    .locator('tr, div[class*="rt-tr"], div[role="row"]')
    .filter({ has: page.locator('input[id^="lineItems"][id$="quantityRequested"]') })
    .last();
  await selectInside(page, row, productName);
  await row.locator('input[id^="lineItems"][id$="quantityRequested"]').fill(String(qty));
  await page.click('button:has-text("Next")');
  await expectActiveStep(page, 'Edit');

  return stockMovementId;
}

/** Waits until the app's blocking loading spinner is gone. */
export async function waitForSpinner(page: Page): Promise<void> {
  await expect(page.locator('.spinner-container')).toBeHidden({ timeout: 60_000 });
}

/** The outbound wizard keeps one URL; the active step shows in the breadcrumb. */
export async function expectActiveStep(page: Page, name: string): Promise<void> {
  await expect(page.locator('.step-container.active .step-name')).toHaveText(name, { timeout: 60_000 });
}

/**
 * Advances the outbound wizard from the Edit step through Pick (picklist is
 * autogenerated on entry) and optional Pack up to the Send step.
 */
export async function advanceToSendStep(page: Page): Promise<void> {
  await page.click('button:has-text("Next")');
  await expectActiveStep(page, 'Pick');
  // Pick -> (Pack ->) Send: keep clicking Next until the send form shows up.
  // The pick/pack tables re-render while loading, so tolerate clicks that get
  // interrupted by a detached button and just retry.
  const sendButton = page.locator('button:has-text("Send shipment")');
  for (let i = 0; i < 4; i += 1) {
    await waitForSpinner(page);
    if (await sendButton.isVisible().catch(() => false)) break;
    await page.locator('button:has-text("Next")').last()
      .click({ timeout: 15_000 })
      .catch(() => {});
    await page.waitForLoadState('networkidle');
  }
  await expectActiveStep(page, 'Send');
  await expect(sendButton).toBeVisible();
}

export async function fetchStockMovement(page: Page, id: string) {
  const res = await page.request.get(url(`/api/stockMovements/${id}`));
  expect(res.status()).toBe(200);
  return (await res.json()).data;
}
