#!/usr/bin/env python3
"""Builds docs/migration/SCREEN_INVENTORY.md from screen_inventory.json
(produced by audit_screens.py)."""
import json
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(HERE, "screen_inventory.json")) as _f:
    DATA = json.load(_f)
OUT = os.path.join(HERE, "..", "SCREEN_INVENTORY.md")

MODULES = {
    "Inventory & Stock": ["inventory", "inventoryBrowser", "inventoryItem", "inventoryLevel", "inventorySnapshot", "transactionEntry", "transaction", "cycleCount", "replenishment", "consumption"],
    "Product Catalog": ["product", "productAssociation", "productCatalog", "productComponent", "productGroup", "productType", "productSupplier", "category", "attribute", "tag", "unitOfMeasureConversion"],
    "Locations & Organizations": ["location", "locationGroup", "locationType", "locationRole", "organization", "party", "partyRole", "partyType", "person", "supplier", "country"],
    "Requisitions & Stocklists": ["requisition", "requisitionItem", "requisitionTemplate", "stocklist", "picklist", "allocation"],
    "Shipments & Receiving": ["shipment", "shipmentItem", "shipmentWorkflow", "createShipmentWorkflow", "receiveOrderWorkflow", "goodsReceiptNote", "deliveryNote", "container", "returns", "stockMovement", "stockTransfer", "partialReceiving", "putAway", "doc4j"],
    "Orders & Finance": ["order", "purchaseOrder", "orderAdjustmentType", "budgetCode", "glAccount", "glAccountType", "paymentTerm", "invoice", "preferenceType", "referenceNumberType"],
    "Reporting": ["report", "dataExport"],
    "Admin & Configuration": ["admin", "user", "role", "auth", "localization", "migration", "jobs", "quartz", "batch", "document", "eventType", "email"],
    "Core Shell & Misc": ["index", "error", "errors", "exception", "unsupported", "dashboard", "mobile", "json", "common", "layouts", "taglib"],
}
MODULE_OF = {}
for mod, dirs in MODULES.items():
    for d in dirs:
        MODULE_OF[d] = mod

BATCH_SIZE = 6

screens = DATA["screens"]
counts = DATA["counts"]


def module_of(key):
    top = key.split("/")[0]
    return MODULE_OF.get(top, "Core Shell & Misc")


live = [s for s in screens if s["classification"] == "LIVE"]
by_module = defaultdict(list)
for s in live:
    by_module[module_of(s["key"])].append(s)

lines = []
lines.append("# OpenBoxes GSP Screen Inventory (Phase 0.4 — Dead-Screen Audit)")
lines.append("")
lines.append("Static-analysis audit of every GSP under `grails-app/views/`. Generated by")
lines.append("[`docs/migration/scripts/audit_screens.py`](scripts/audit_screens.py) and")
lines.append("[`docs/migration/scripts/build_inventory_md.py`](scripts/build_inventory_md.py);")
lines.append("raw data in [`docs/migration/scripts/screen_inventory.json`](scripts/screen_inventory.json).")
lines.append("")
lines.append("## Methodology")
lines.append("")
lines.append("Each GSP was classified using the following evidence sources:")
lines.append("")
lines.append("- **Controller actions** (Grails convention `views/<controller>/<action>.gsp`), including old closure-style and webflow (`*Flow`) state views")
lines.append("- **URL mappings** (`grails-app/controllers/org/pih/warehouse/UrlMappings.groovy`)")
lines.append("- **Explicit `render(view:)` / `render(template:)`** calls in controllers, services, and taglibs (including template paths passed as plain string arguments)")
lines.append("- **Menu / navigation references** (`grails-app/conf/runtime.groovy` megamenu, `_menu.gsp`, layouts)")
lines.append("- **`g:link` / `g:include` / redirect references** across all GSPs and Groovy sources")
lines.append("- **Template inclusion graph** (`g:render template=`, `tmpl.`, `g:applyLayout`, layout `meta` tags) resolved to a fixpoint — a `_template.gsp` is only counted live if transitively included by a live page")
lines.append("- **React SPA routes** (`src/js/components/Router.jsx`) to detect screens superseded by the SPA")
lines.append("")
lines.append("Classifications:")
lines.append("")
lines.append("| Classification | Meaning |")
lines.append("|---|---|")
lines.append("| **LIVE** | User-reachable screen (routed controller action, menu link, explicit render, or link reference) |")
lines.append("| **TEMPLATE** | Partial/layout included (transitively) by a live page |")
lines.append("| **SUPERSEDED** | GSP still exists but the route is served by the React SPA |")
lines.append("| **DEAD** | No route, menu, render, or include reference found |")
lines.append("")
lines.append("## Summary")
lines.append("")
lines.append("| Classification | Count |")
lines.append("|---|---|")
total = 0
for cls in ("LIVE", "TEMPLATE", "SUPERSEDED", "DEAD"):
    lines.append(f"| {cls} | {counts.get(cls, 0)} |")
    total += counts.get(cls, 0)
lines.append(f"| **Total** | **{total}** |")
lines.append("")
lines.append(f"The migration-relevant surface is **{counts.get('LIVE', 0)} live screens** (plus {counts.get('TEMPLATE', 0)} supporting templates that are included by them). "
             f"{counts.get('DEAD', 0)} GSPs have no discoverable references and are candidates for deletion; {counts.get('SUPERSEDED', 0)} have already been replaced by React SPA routes.")
lines.append("")
lines.append("> Note: the pre-audit expectation was ~350–450 live screens of 616. The evidence shows fewer standalone LIVE screens (many GSPs are `_partial` templates rather than full screens); LIVE + TEMPLATE together = "
             f"{counts.get('LIVE', 0) + counts.get('TEMPLATE', 0)} GSPs of user-facing surface.")
lines.append("")

# --------------------------------------------------------- phase 2 work queue
lines.append("## Phase 2 Module-Batch Work Queue (LIVE screens)")
lines.append("")
lines.append(f"LIVE screens grouped into migration batches of up to {BATCH_SIZE} related screens.")
lines.append("Suggested order: high-traffic operational modules first, admin/reference data later.")
lines.append("")
MISSING_API = {
    "Inventory & Stock": "transaction listing/editing (`TransactionApi` absent; only snapshot/summary APIs exist)",
    "Requisitions & Stocklists": "legacy requisition webflow endpoints (React uses StockMovementApi; no dedicated RequisitionApi for the classic flow)",
    "Shipments & Receiving": "createShipmentWorkflow webflow states have no API equivalents (React covers stockMovement/partialReceiving only)",
    "Orders & Finance": "order adjustment types, budget codes, payment terms lack CRUD APIs (only select-options endpoints)",
    "Reporting": "most reports render server-side (no JSON API; only dashboard indicator APIs exist)",
    "Admin & Configuration": "admin console actions (cache, settings, jobs/quartz) have no API endpoints",
    "Locations & Organizations": "party/partyRole/partyType CRUD has no API (LocationApi and OrganizationApi exist)",
    "Product Catalog": "attribute/tag/unitOfMeasureConversion management APIs partial (AttributeApi exists; UoM conversions do not)",
    "Core Shell & Misc": "none — mostly shell/error pages",
}
batch_no = 0
order = ["Inventory & Stock", "Product Catalog", "Requisitions & Stocklists", "Shipments & Receiving", "Orders & Finance", "Locations & Organizations", "Reporting", "Admin & Configuration", "Core Shell & Misc"]
for mod in order:
    ss = sorted(by_module.get(mod, []), key=lambda s: s["key"])
    if not ss:
        continue
    lines.append(f"### {mod} ({len(ss)} screens)")
    lines.append("")
    lines.append(f"*Potentially missing APIs: {MISSING_API.get(mod, 'none identified')}*")
    lines.append("")
    for i in range(0, len(ss), BATCH_SIZE):
        batch_no += 1
        chunk = ss[i:i + BATCH_SIZE]
        names = ", ".join("`" + s["key"] + "`" for s in chunk)
        lines.append(f"- **Batch {batch_no}** — {names}")
    lines.append("")

# ------------------------------------------------------------------ full table
lines.append("## Full Inventory")
lines.append("")
lines.append("| GSP path | Classification | Evidence (file:line) | Module group |")
lines.append("|---|---|---|---|")
for s in sorted(screens, key=lambda s: (s["classification"], s["key"])):
    ev = s["evidence"].replace("|", "\\|")
    lines.append(f"| `{s['gsp']}` | {s['classification']} | {ev} | {module_of(s['key'])} |")
lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("wrote", os.path.abspath(OUT), f"({batch_no} batches)")
